compiler-check: match-exact
resolver: lts-12.0
require-stack-version: ! '>=1.6'

flags:
  rfc-prelude:
      production: false
  wai-cli:
      tls: false
  postgresql-typed:
      hdbc: false
  postgresql-binary:
      hdbc: false
  base:
      integer-gmp: true
  aeson:
      cffi: true
      fast: false
      developer: false
  cryptonite:
      support_pclmuldq: true
  zlib:
      non-blocking-ffi: true
  tls:
      compat: false

extra-package-dbs: []
packages:
- '.'
extra-deps:  
- time-units-1.0.0
- url-2.1.3
- file-embed-lzma-0
- git: git@github.com:RobertFischer/rfc.git
  commit: 8bcbfd2
  subdirs:
    - rfc-prelude
