resolver: lts-7.19
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
compiler-check: match-minor # Be sure you also have this line in ~/.stack/config.yaml (match-minor also works for either/both)

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007019_ghc-8.0.1:
           url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
           sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9

packages:
 - '.'
extra-deps:
- lens-4.16
- megaparsec-6.4.1
- miso-0.15.0.0
- rfc-0.0.0.25
- aeson-diff-1.1.0.4
- classy-prelude-1.4.0
- http-api-data-0.3.8.1
- lifted-async-0.10.0.1
- monad-control-1.0.2.3
- natural-transformation-0.4
- parser-combinators-0.4.0
- profunctors-5.2.2
- servant-0.12.1
- th-abstraction-0.2.6.0
- time-units-1.0.0
- unliftio-0.2.6.0
- unliftio-core-0.1.1.0
- async-2.2.1
- attoparsec-iso8601-1.0.0.0
- basic-prelude-0.7.0
- cabal-doctest-1.0.6
- edit-distance-vector-1.0.0.4
